.PHONY: help check check-env authoritative-source-check scanner-test workspace-bootstrap context-refresh github-context dist

.DEFAULT_GOAL := check

WORKSPACE_REPOS_MANIFEST := config/workspace-repos.txt

WORKSPACE_BOOTSTRAP_SOURCES := \
	docs/start-here.md \
	docs/engineering-baseline.md \
	docs/repo-readiness.md \
	docs/context-refresh.md \
	docs/tool-adapters/codex.md \
	docs/maintenance-automations.md \
	docs/prompts.md

help: ## List available repo-local Makefile targets with short descriptions.
	@awk 'BEGIN {FS = ":.*## "}; /^[a-zA-Z0-9_.-]+:.*## / {printf "  %-28s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

check: ## Run canonical local validation for local work and CI.
	@if command -v markdownlint-cli2 >/dev/null 2>&1; then \
		echo "Running markdownlint-cli2"; \
		markdownlint-cli2 "**/*.md" "#dist"; \
	elif command -v markdownlint >/dev/null 2>&1; then \
		echo "Running markdownlint"; \
		markdownlint --ignore dist "**/*.md"; \
	else \
		echo "markdownlint is not installed."; \
		echo "Install markdownlint-cli2 or markdownlint, then rerun 'make check'."; \
		exit 1; \
	fi
	PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover -s tests

check-env: ## Verify local tools needed by make check are available.
	@if command -v markdownlint-cli2 >/dev/null 2>&1; then \
		echo "Found markdownlint-cli2"; \
	elif command -v markdownlint >/dev/null 2>&1; then \
		echo "Found markdownlint"; \
	else \
		echo "markdownlint is not installed."; \
		echo "Install markdownlint-cli2 or markdownlint to enable local validation."; \
		exit 1; \
	fi

authoritative-source-check: ## Run advisory authoritative-source scanning.
	python3 scripts/check_authoritative_sources.py --base-ref origin/main --head-ref HEAD

scanner-test: ## Run scanner unit tests.
	PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover -s tests

workspace-bootstrap: ## Generate fresh-thread and project-source bootstrap context.
	@set -eu; \
	for src in $(WORKSPACE_BOOTSTRAP_SOURCES); do \
		if [ ! -f "$$src" ]; then \
			echo "Missing source document: $$src" >&2; \
			exit 1; \
		fi; \
	done; \
	mkdir -p dist; \
	out="dist/workspace-bootstrap.md"; \
	tmp="$$out.tmp"; \
	{ \
		printf '%s\n' '# Workspace Bootstrap Context'; \
		printf '%s\n' ''; \
		printf '%s\n' 'Status: generated snapshot'; \
		printf '%s\n' 'Canonical: false'; \
		printf '%s\n' ''; \
		printf '%s\n' 'This file is a generated convenience bundle for fresh-thread and project-source context bootstrapping.'; \
		printf '%s\n' ''; \
		printf '%s\n' 'Canonical guidance remains in:'; \
		printf '%s\n' '- `ai-workflow-playbook`'; \
		printf '%s\n' '- repo-local `AGENTS.md`'; \
		printf '%s\n' ''; \
		printf '%s\n' 'Do not edit this file directly. Regenerate it with `make workspace-bootstrap`.'; \
		for src in $(WORKSPACE_BOOTSTRAP_SOURCES); do \
			printf '%s\n' ''; \
			printf '%s\n' '---'; \
			printf '%s\n' ''; \
			printf '## Source: `%s`\n\n' "$$src"; \
			cat "$$src"; \
			printf '%s\n' ''; \
		done; \
	} > "$$tmp"; \
	mv "$$tmp" "$$out"; \
	echo "Generated $$out"

context-refresh: ## Generate current-state brief for fresh-thread handoff.
	python3 scripts/generate_context_refresh.py --repo-manifest $(WORKSPACE_REPOS_MANIFEST) --output dist/context-refresh.md

github-context: ## Generate GitHub connector repo hydration snippet.
	python3 scripts/generate_github_context.py --repo-manifest $(WORKSPACE_REPOS_MANIFEST) --output dist/github-context.md

dist: workspace-bootstrap context-refresh github-context ## Generate all distribution context artifacts.
