.PHONY: check check-env authoritative-source-check scanner-test workspace-bootstrap context-refresh

WORKSPACE_BOOTSTRAP_SOURCES := \
	docs/start-here.md \
	docs/engineering-baseline.md \
	docs/repo-readiness.md \
	docs/context-refresh.md \
	docs/tool-adapters/codex.md \
	docs/maintenance-automations.md \
	docs/prompts.md

# Canonical validation entrypoint for local work and CI.
check:
	@if command -v markdownlint-cli2 >/dev/null 2>&1; then \
		echo "Running markdownlint-cli2"; \
		markdownlint-cli2 "**/*.md" "#dist"; \
	elif command -v markdownlint >/dev/null 2>&1; then \
		echo "Running markdownlint"; \
		markdownlint --ignore dist "**/*.md"; \
	else \
		echo "markdownlint is not installed."; \
		echo "Install markdownlint-cli2 or markdownlint, then rerun 'make check'."; \
		exit 1; \
	fi
	PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover -s tests

# Environment probe for the tool behind check; not a validation substitute.
check-env:
	@if command -v markdownlint-cli2 >/dev/null 2>&1; then \
		echo "Found markdownlint-cli2"; \
	elif command -v markdownlint >/dev/null 2>&1; then \
		echo "Found markdownlint"; \
	else \
		echo "markdownlint is not installed."; \
		echo "Install markdownlint-cli2 or markdownlint to enable local validation."; \
		exit 1; \
	fi

# Advisory source scan; CI runs this separately from required make check.
authoritative-source-check:
	python3 scripts/check_authoritative_sources.py --base-ref origin/main --head-ref HEAD

scanner-test:
	PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover -s tests

# Generated convenience bundle for fresh-thread and project-source hydration.
workspace-bootstrap:
	@set -eu; \
	for src in $(WORKSPACE_BOOTSTRAP_SOURCES); do \
		if [ ! -f "$$src" ]; then \
			echo "Missing source document: $$src" >&2; \
			exit 1; \
		fi; \
	done; \
	mkdir -p dist; \
	out="dist/workspace-bootstrap.md"; \
	tmp="$$out.tmp"; \
	{ \
		printf '%s\n' '# Workspace Bootstrap Context'; \
		printf '%s\n' ''; \
		printf '%s\n' 'Status: generated snapshot'; \
		printf '%s\n' 'Canonical: false'; \
		printf '%s\n' ''; \
		printf '%s\n' 'This file is a generated convenience bundle for fresh-thread and project-source context bootstrapping.'; \
		printf '%s\n' ''; \
		printf '%s\n' 'Canonical guidance remains in:'; \
		printf '%s\n' '- `ai-workflow-playbook`'; \
		printf '%s\n' '- repo-local `AGENTS.md`'; \
		printf '%s\n' ''; \
		printf '%s\n' 'Do not edit this file directly. Regenerate it with `make workspace-bootstrap`.'; \
		for src in $(WORKSPACE_BOOTSTRAP_SOURCES); do \
			printf '%s\n' ''; \
			printf '%s\n' '---'; \
			printf '%s\n' ''; \
			printf '## Source: `%s`\n\n' "$$src"; \
			cat "$$src"; \
			printf '%s\n' ''; \
		done; \
	} > "$$tmp"; \
	mv "$$tmp" "$$out"; \
	echo "Generated $$out"

# Generated current-state brief for fresh-thread handoff.
context-refresh:
	python3 scripts/generate_context_refresh.py --output dist/context-refresh.md
