from __future__ import annotations

from datetime import datetime, timezone
import importlib.util
from pathlib import Path
import sys
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

SCRIPT_PATH = SCRIPTS_DIR / "generate_context_refresh.py"
SPEC = importlib.util.spec_from_file_location("generate_context_refresh", SCRIPT_PATH)
assert SPEC is not None
generator = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = generator
SPEC.loader.exec_module(generator)


class ContextRefreshGeneratorTest(unittest.TestCase):
    def test_report_starts_with_required_header(self) -> None:
        report = generator.render_report(
            reports=[],
            unavailable=[],
            generated_at=datetime(2026, 5, 8, 12, 0, tzinfo=timezone.utc),
            repos=("ctrl-alt-keith/example",),
        )

        self.assertTrue(
            report.startswith(
                "\n".join(
                    [
                        "# Context Refresh",
                        "",
                        "Status: generated snapshot",
                        "Canonical: false",
                        "",
                        (
                            "This file is a generated repository orientation "
                            "brief for fresh-thread handoff."
                        ),
                        "",
                        (
                            "Repository code, issues, pull requests, and docs remain "
                            "the source of truth."
                        ),
                        "",
                        (
                            "Do not edit this file directly. Regenerate it with "
                            "`make context-refresh`."
                        ),
                    ]
                )
            )
        )

    def test_report_lists_unavailable_repos(self) -> None:
        report = generator.render_report(
            reports=[],
            unavailable=[
                generator.UnavailableRepo(
                    "ctrl-alt-keith/example",
                    "repository was not returned by GitHub",
                )
            ],
            generated_at=datetime(2026, 5, 8, 12, 0, tzinfo=timezone.utc),
            repos=("ctrl-alt-keith/example",),
        )

        self.assertIn("## Blocked Or Unavailable", report)
        self.assertIn(
            "- `ctrl-alt-keith/example`: repository was not returned by GitHub",
            report,
        )

    def test_repo_state_omits_dynamic_pr_issue_details(self) -> None:
        report = generator.render_report(
            reports=[
                generator.RepoReport(
                    "ctrl-alt-keith/example",
                    "main",
                )
            ],
            unavailable=[],
            generated_at=datetime(2026, 5, 8, 12, 0, tzinfo=timezone.utc),
            repos=("ctrl-alt-keith/example",),
        )

        self.assertIn("- Default branch: `main`", report)
        self.assertIn(
            (
                "- Dynamic PR/issue state intentionally omitted; inspect "
                "GitHub directly before acting."
            ),
            report,
        )
        self.assertNotIn("Open PRs", report)
        self.assertNotIn("Open Issues", report)
        self.assertNotIn("Recent Merged PRs", report)
        self.assertNotIn("author:", report)
        self.assertNotIn("updatedAt", report)

    def test_one_line_normalizes_whitespace(self) -> None:
        self.assertEqual(generator.one_line("hello\n  there"), "hello there")


if __name__ == "__main__":
    unittest.main()
