from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Any

from workspace_repos import (
    WorkspaceRepoManifestError,
    read_workspace_repos,
)

DEFAULT_MANIFEST = Path("config/workspace-repos.txt")

REPO_CONTEXT_QUERY = """
query RepoContext($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    defaultBranchRef {
      name
    }
  }
}
"""


@dataclass(frozen=True)
class RepoReport:
    name: str
    default_branch: str | None


@dataclass(frozen=True)
class UnavailableRepo:
    name: str
    reason: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a non-canonical repository orientation refresh."
    )
    parser.add_argument(
        "--output",
        default="dist/context-refresh.md",
        type=Path,
        help="Markdown file to write.",
    )
    parser.add_argument(
        "--repo-manifest",
        default=DEFAULT_MANIFEST,
        type=Path,
        help="Workspace repo manifest to read.",
    )
    return parser.parse_args()


def require_gh() -> None:
    if shutil.which("gh") is None:
        raise RuntimeError("GitHub CLI `gh` is required for make context-refresh.")

    result = subprocess.run(
        ["gh", "auth", "status"],
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode != 0:
        detail = one_line(result.stderr or result.stdout or "unknown auth failure")
        raise RuntimeError(f"GitHub CLI is not authenticated: {detail}")


def run_graphql(owner: str, name: str) -> dict[str, Any]:
    result = subprocess.run(
        [
            "gh",
            "api",
            "graphql",
            "-F",
            f"owner={owner}",
            "-F",
            f"name={name}",
            "-f",
            f"query={REPO_CONTEXT_QUERY}",
        ],
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode != 0:
        detail = one_line(result.stderr or result.stdout or "query failed")
        raise RuntimeError(detail)

    payload = json.loads(result.stdout)
    if payload.get("errors"):
        detail = one_line(json.dumps(payload["errors"], sort_keys=True))
        raise RuntimeError(detail)

    repository = payload.get("data", {}).get("repository")
    if not repository:
        raise RuntimeError("repository was not returned by GitHub")
    return repository


def collect_repo(repo: str) -> RepoReport:
    owner, name = repo.split("/", 1)
    repository = run_graphql(owner, name)
    default_branch = repository.get("defaultBranchRef") or {}
    return RepoReport(
        name=repo,
        default_branch=default_branch.get("name"),
    )


def collect_reports(repos: tuple[str, ...]) -> tuple[list[RepoReport], list[UnavailableRepo]]:
    reports: list[RepoReport] = []
    unavailable: list[UnavailableRepo] = []
    for repo in repos:
        try:
            reports.append(collect_repo(repo))
        except Exception as exc:
            unavailable.append(UnavailableRepo(repo, one_line(str(exc))))
    return reports, unavailable


def render_report(
    reports: list[RepoReport],
    unavailable: list[UnavailableRepo],
    generated_at: datetime,
    repos: tuple[str, ...],
) -> str:
    timestamp = generated_at.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Context Refresh",
        "",
        "Status: generated snapshot",
        "Canonical: false",
        "",
        "This file is a generated repository orientation brief for fresh-thread handoff.",
        "",
        "Repository code, issues, pull requests, and docs remain the source of truth.",
        "",
        "Do not edit this file directly. Regenerate it with `make context-refresh`.",
        "",
        f"Generated: {timestamp}",
        "",
        "## Snapshot Notice",
        "",
        "This report is a point-in-time snapshot, not canonical guidance.",
        "Use GitHub and repository state as the source of truth before acting.",
        "Dynamic PR/issue state intentionally omitted; inspect GitHub directly before acting.",
        "",
        "## Tracked Repositories",
        "",
    ]
    lines.extend(f"- `{repo}`" for repo in repos)
    lines.extend(["", "## Repository State", ""])

    by_name = {report.name: report for report in reports}
    for repo in repos:
        report = by_name.get(repo)
        if report is None:
            continue
        lines.extend(render_repo(report))
        lines.append("")

    if unavailable:
        lines.extend(["## Blocked Or Unavailable", ""])
        lines.extend(
            f"- `{repo.name}`: {repo.reason}"
            for repo in unavailable
        )
        lines.append("")

    lines.extend(
        [
            "## Reminder",
            "",
            "This file is a generated convenience artifact.",
            "It is useful for fresh-thread handoff and repo orientation refresh,",
            "but it does not replace repository docs, issues, pull requests,",
            "or current GitHub state.",
            "",
        ]
    )
    return "\n".join(lines)


def render_repo(report: RepoReport) -> list[str]:
    lines = [
        f"### `{report.name}`",
        "",
        f"- Default branch: `{report.default_branch or 'unknown'}`",
        "- Dynamic PR/issue state intentionally omitted; inspect GitHub directly before acting.",
    ]
    return lines


def one_line(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def write_report(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f"{output.name}.tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(output)


def main() -> int:
    args = parse_args()
    try:
        repos = read_workspace_repos(args.repo_manifest)
        require_gh()
        reports, unavailable = collect_reports(repos)
        content = render_report(
            reports,
            unavailable,
            datetime.now(timezone.utc),
            repos,
        )
        write_report(args.output, content)
    except WorkspaceRepoManifestError as exc:
        print(f"context-refresh failed: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"context-refresh failed: {exc}", file=sys.stderr)
        return 1

    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
