from __future__ import annotations

import argparse
from pathlib import Path
import sys


DEFAULT_SOURCES = (
    Path("docs/start-here.md"),
    Path("docs/engineering-baseline.md"),
    Path("docs/repo-readiness.md"),
    Path("docs/context-refresh.md"),
    Path("docs/tool-adapters/codex.md"),
    Path("docs/maintenance-automations.md"),
    Path("docs/prompts.md"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the non-canonical workspace bootstrap context bundle."
    )
    parser.add_argument(
        "--output",
        default=Path("dist/workspace-bootstrap.md"),
        type=Path,
        help="Markdown file to write.",
    )
    return parser.parse_args()


def render_workspace_bootstrap(sources: tuple[Path, ...] = DEFAULT_SOURCES) -> str:
    lines = [
        "# Workspace Bootstrap Context",
        "",
        "Status: generated snapshot",
        "Canonical: false",
        "",
        (
            "This file is a generated convenience bundle for fresh-thread and "
            "project-source context bootstrapping."
        ),
        "",
        "Canonical guidance remains in:",
        "- `ai-workflow-playbook`",
        "- repo-local `AGENTS.md`",
        "",
        "Do not edit this file directly. Regenerate it with `make workspace-bootstrap`.",
    ]

    for source in sources:
        if not source.is_file():
            raise FileNotFoundError(f"Missing source document: {source}")
        lines.extend(
            [
                "",
                "---",
                "",
                f"## Source: `{source}`",
                "",
                source.read_text(encoding="utf-8"),
                "",
            ]
        )

    return "\n".join(lines)


def write_report(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f"{output.name}.tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(output)


def main() -> int:
    args = parse_args()
    try:
        write_report(args.output, render_workspace_bootstrap())
    except Exception as exc:
        print(f"workspace-bootstrap failed: {exc}", file=sys.stderr)
        return 1

    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
