from __future__ import annotations

import argparse
from pathlib import Path
import sys

from workspace_repos import (
    WorkspaceRepoManifestError,
    read_workspace_repos,
)


DEFAULT_MANIFEST = Path("config/workspace-repos.txt")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a noncanonical GitHub connector context snippet."
    )
    parser.add_argument(
        "--output",
        default="dist/github-context.md",
        type=Path,
        help="Markdown file to write.",
    )
    parser.add_argument(
        "--repo-manifest",
        default=DEFAULT_MANIFEST,
        type=Path,
        help="Workspace repo manifest to read.",
    )
    return parser.parse_args()


def render_github_context(repos: tuple[str, ...]) -> str:
    lines = [
        "# GitHub Connector Context",
        "",
        "Status: generated snapshot",
        "Canonical: false",
        "",
        "This file is a generated convenience artifact for refreshing GitHub connector repo context in fresh threads.",
        "",
        "Canonical guidance remains in:",
        "- `ai-workflow-playbook`",
        "- repo-local `AGENTS.md`",
        "",
        "Do not edit this file directly. Regenerate it with `make github-context`.",
        "",
        "```text",
    ]
    lines.extend(f"@GitHub {repo}" for repo in repos)
    lines.extend(["```", ""])
    return "\n".join(lines)


def write_report(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f"{output.name}.tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(output)


def main() -> int:
    args = parse_args()
    try:
        repos = read_workspace_repos(args.repo_manifest)
        content = render_github_context(repos)
        write_report(args.output, content)
    except WorkspaceRepoManifestError as exc:
        print(f"github-context failed: {exc}", file=sys.stderr)
        return 1

    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
