name: Markdown Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install markdownlint-cli2
        run: npm install --global markdownlint-cli2

      - name: Run checks
        run: make check
